GET {{host}}:{{port}}/api/products
Accept: application/json

### Search by Category ID

GET {{host}}:{{port}}/api/products/search/findByCategoryId?id=2
Accept: application/json

### Search by name

GET {{host}}:{{port}}/api/products/search/findByNameContaining?name=Python
Accept: application/json
